### ISSUE TITLE
Architecture ideas and contributing

### ISSUE THREAD

**Issue by TimothyKrell** [BerkeleyTrue/react-material#80]
Following up from conversations on [twitter](https://twitter.com/Sander_Spies/status/571689515963842562), I'm really interested in contributing to react-material and getting it up to parity with [angular material](https://material.angularjs.org/#/). This is the one thing I miss from Angular. 
- I'd love to see a really good theming story like angular-material has.
  - Browsing through the code I saw you have some kind of theming going, but I need to figure out how it integrates with components.
  - I liked some of the discussion here on [implementing theming](https://github.com/callemall/material-ui/issues/30#issuecomment-76510428).
- Angular material's [conveniences for layout](https://material.angularjs.org/#/layout/container) are nice. Maybe we could make components like `<row>` or `<container>` for this? I'm not positive this would be better than just letting people define the flexbox layouts themselves. It could be a nice start for new people to the framework to be able to get up and running with a standard app layout easily, though.
- I noticed IE8 support is one of your goals, but I wonder if that may cause too many difficulties to making nice implementations of the components. I definitely don't have a strong a opinion on this, but it seems like a lot of other libraries aren't bothering with IE8 anymore?
- I like how angular-material puts tests alongside its directives. Did you have any thoughts on what to use for testing?
- I really like how react-material is putting styles in the js. I'm wondering if something like [Radium](http://projects.formidablelabs.com/radium/) might be a better option than react-style.
  - Radium has a nice way of handling computed styles, states, and media queries with support coming for keyframe animations. 
  - Maybe react-style has these coming?
- Thanks for this cool library! I don't have much experience designing libraries, but I want to learn and help make a great material design lib for React! Where can I start contributing?

**Comment by phated** [comment]
Just 1 comment about inline styles/react-styles/radium - during my attempt at starting some material design components, I tried [JSS](https://github.com/jsstyles/jss), and I was very happy with it.  Thoughts on actual styles vs inline?

**Comment by TimothyKrell** [comment]
I'll definitely put in a plug for JSS. I have been using it on my project and liking it. One plus with it is you don't need to have work arounds for keyframe animations or media queries, because you can just add them as normal css into a style tag that is added to the top of the page.

**Comment by SanderSpies** [comment]
Sorry guys, but React Material isn't going to use JSS or Radium. I'm happy with the current React Style syntax: https://github.com/SanderSpies/react-material/blob/0.13/components/Button.js. Animations should be solved using a JavaScript solution, and react-magician is my attempt at this: https://github.com/SanderSpies/react-magician. This way you can also control animations using touch, which isn't possible with CSS animations. React magician supports the animation part for this, the touch library is something I still need to implement (https://github.com/SanderSpies/momentum is where that will be). Media queries should be implemented inside the render function, a simple Screen.width will do the trick most of the time. I'm still looking for a better solution though - that can be used for both inline styles and css

**Layout blocks** sound like a great idea, perhaps we can take some inspiration from https://github.com/reactjs/react-future/tree/master/04%20-%20Layout. Preferably using Flex Box, so yes that would mean dropping old IE versions.

**Theming** is an interesting challenge, something like `ReactMaterial.setThemeColors({primary1: Colors.blue.p500, accent: Colors.blue.a100})` would be a great starting point I think? (Inspiration taken from Angular Material). 

For **testing** I would prefer to use Jest as it has good React support out of the box, but not really a strong opinion here.

Let me know what you want to take a shot at, please fork the 0.13 branch (which is the upcoming version with support React 0.13 and new React Style).

**Comment by TimothyKrell** [comment]
Thanks for the detailed reply. This all sounds great! I like the strategy you outlined for using React style. I'd imagine using react-magician would give the advantage of providing a lot of reusable animations that a user could plug into their own designs. 

Just one question on styling: how would we deal with providing base styling for generic html tags (e.g. font sizes and styling for header tags and `<p>` tags)?

I'd like to get my feet wet by trying to implement some basic, missing components. I need a progress bar in my app currently, but it looks like there is one there already. Does it needs some work or is it pretty much done? What other components do think would be good to start on? I'd also be willing to make the documentation nicer if you can point me in the right direction.

**Comment by SanderSpies** [comment]
@TimothyKrell ideally we should have tags for headers and paragraphs, with default but overridable sizes. 

If you look at the Progress Bar: http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators you'll notice we don't support everything yet. So this could definitely use work :+1:. It could be a good idea to get started with that and see where that goes. It's really up to you what you want to pick up though :-). 

I'll be focusing a bit more on the underlying systems, I hope to get something up soonish for touch momentum support.

**Comment by natew** [comment]
Subbing to this thread

@SanderSpies once I begin work on the material theme, would you mind if I used this repo as a start point (colors and looking at techniques)? The reapp theme structure is pretty well defined so it should be just dropping in, setting constants, etc.

As for animations I use react-tween-state, in combination with a scroller library when necessary. But I'm keeping an eye on magician. I haven't had a need for it yet, but I could see external users using it.

**Comment by SanderSpies** [comment]
@natew That would be great, if you got good ideas I definitely like to hear them :+1:

**Comment by BerkeleyTrue** [comment]
I would like to add waffle.io for project manegement. I have comeback to this project only to be turned off due to not knowing the direction this or react-style project is going. If it helps I can set it up. We use it for [FreeCodeCamp](https://github.com/FreeCodeCamp/freecodecamp/) with lots of success.

**Comment by SanderSpies** [comment]
@BerkeleyTrue thanks for being honest.

Regarding React Style: a new version will arrive closely after React 0.13 - which React Material will also use. This version will be aligned with the ideas of @vjeux. I'm expecting it to be mostly what's on GH right now inside the inline-styles branch. After this release, I'm hoping to work together with @jscheid to add support for media queries and CSS source-maps. Hope that clarifies where React Style is going :-).

As for React Material, the idea is still the same: recreate the Material Design components mentioned here: http://www.google.com/design/spec/material-design/introduction.html. I want to do this the best way possible, so my work is mostly focused on the underlying systems to enable this for now:
- React Style for styling
- React Magician for animation
- momentum for touch momentum support
- layout blocks as mentioned by @TimothyKrell would also be an important underlying system, but I would like someone else to take the lead there :-)

Hopefully this will make it possible to start working on recreating existing Material design applications with preferably no compromises. 

If waffle.io helps with clarifying what's happening: let's do that!

Is there anything you would like to work on?

**Comment by BerkeleyTrue** [comment]
My projects always rely on server side rendering and the last time I attempted to use this project I ran into issues as it RM relies heavily on webpack to overload require statement. I would love to revisit this project and make it as bundler agnostic as possible. 

If there are no objections I think I will work on that first. 

I will also add waffle board to project if no one objections.

**Comment by SanderSpies** [comment]
@BerkeleyTrue What's RM? I'm not familiair with that term :-).

**Comment by BerkeleyTrue** [comment]
React Material, sorry.

**Comment by SanderSpies** [comment]
Lol, that was too obvious. How would you want to make it bundler agnostic?
Op 12 mrt. 2015 08:26 schreef "Berkeley Martinez" <notifications@github.com

**Comment by BerkeleyTrue** [comment]
For instance, [this](https://github.com/SanderSpies/react-material/blob/0.13/components/src/Icon.js#L6) will prevent server side rendering and browserify. What I usually do is turn svg icons into react comp that render svg's directly, like [so](https://github.com/r3dm/r3dm.com/blob/master/components/logo/LogoType.jsx)

**Comment by SanderSpies** [comment]
@BerkeleyTrue - yes, please! (preferably in an automated way :+1: )

**Comment by BerkeleyTrue** [comment]
Automation will be tough. I will see what I can do. This should all be done in 0.13 branch as well?

**Comment by SanderSpies** [comment]
Yes please, these are some build issues though (caused by merging
https://github.com/SanderSpies/react-material/pull/87).

On Thu, Mar 12, 2015 at 9:20 AM, Berkeley Martinez <notifications@github.com

**Comment by phated** [comment]
@SanderSpies I'm currently using the build from #87, what issues are you seeing?

**Comment by TimothyKrell** [comment]
Looks like two files were the culprits, preventing webpack from compiling? I created #92 to fix.
