### ISSUE TITLE
Possible memory leak with RippleContainer

### ISSUE THREAD

**Issue by phated** [BerkeleyTrue/react-material#85]
I've been working with the List and ListItem components and end up with immediate tab crashes.  When I add the `disableRipple` property to the ListItem component, I no longer have the crashing.  Haven't dug into why or where this is happening inside of RippleContainer.

**Comment by SanderSpies** [comment]
Yeah, some ugly DOM event listeners are being used which might be the reason for these errors. Wish we could use React's nice virtual event system here.
