### ISSUE TITLE
All components should allow styles to be added or overridden

### ISSUE THREAD

**Issue by phated** [BerkeleyTrue/react-material#86]
Working with the Card component, I noticed that I was unable to pass `styles` to it and override or add to the default styles.  Every component should allow for styles to be overridden or added.

**Comment by SanderSpies** [comment]
Yes definitely, in our case it actually might make sense to have a parent component from which all components inherit as we are in control of the parent component. So something like: 
```
class Button extends MaterialComponent
...
class MaterialComponent extends React.Component
````
might make sense.

**Comment by BerkeleyTrue** [comment]
@SanderSpies I think having HOC instead of creating more subclasses would be better. Something to think about.
