### ISSUE TITLE
Merge 0.13 branch to master and cut a release?

### ISSUE THREAD

**Issue by phated** [BerkeleyTrue/react-material#94]
Now that React 0.13 is officially out, do you think it makes sense to merge the 0.13 branch into master and release a new version?  I am currently depending on a fork with built source, but it'd be much better to depend on a published version.

**Comment by SanderSpies** [comment]
Will do.

**Comment by BerkeleyTrue** [comment]
@SanderSpies Any word on when this can happen. I would do it but I don't think I have the permission too.
