### ISSUE TITLE
react-native support ? 

### ISSUE THREAD

**Issue by mydearxym** [BerkeleyTrue/react-material#96]
amazing work!
is this component support react-native?

**Comment by BerkeleyTrue** [comment]
@mydearxym At the moment this does not support react-native but it definitely should! There are hints that react is moving to make it easier for projects to work on both so it may be prudent to wait for 0.14 to land to make any decisions.

**Comment by BerkeleyTrue** [comment]
for reference: https://github.com/facebook/react/issues/3220
